let cartasMTG =[
{carta: "Edgar Markov",costo:5,autor:"Volkan Baga",disponibilidad: true,comandante:true},
{carta: "Markov Baron", costo: 3, autor: "Ina Wong", disponibilidad: true, comandante: false},
{carta: "Sanctum Seeker", costo: 4, autor: "Volcan Vaga", disponibilidad: true, comandante: false},
{carta: "Kalitas Traidor of Ghet", costo: 4, autor: "Todo Lockwood", disponibilidad: true, comandante: false},
{carta: "Blood Artist", costo: 2, autor: "Johannes Voss", disponibilidad: true, comandante: false},
{carta: "Clavileño First of the Blessed", costo: 3, autor: "Chun Lo", disponibilidad: true, comandante: false},
{carta: "Gifted Aetherborn", costo: 2, autor: "Ryan Lee", disponibilidad: true, comandante: false},
{carta: "Forerunner of the Legion", costo: 3, autor: "Jhos Hass", disponibilidad: true, comandante: false},
{carta: "Rakish Heir", costo: 3, autor: "Winona Nelson", disponibilidad: true, comandante: false},
{carta: "Tarmo Hack", costo: 3, autor: "Henwa Chloe", disponibilidad: true, comandante: false},
{carta: "Drana Liberadora de Malakir", costo: 3, autor: "Mike Bierek", disponibilidad: true, comandante: false},
{carta: "Captivating Vampire", costo: 3, autor: "Erick Deschamp", disponibilidad: true, comandante: false},
{carta: "Drana and Livana", costo: 4, autor: "Raluca Mrinesuko", disponibilidad: true, comandante: false},
{carta: "Asylum Visitor", costo: 2, autor: "Bastien L. Deharme", disponibilidad: true, comandante: false},
{carta: "Viscera Seer", costo: 1, autor: "Jhon Stanko", disponibilidad: true, comandante: false},
{carta: "Vampire Nocturnus", costo: 4, autor: "Raymond Swanland", disponibilidad: true, comandante: false},
{carta: "Stormkirk Captain", costo: 3, autor: "Jana Schirmer and Johannes Voss", disponibilidad: true, comandante: false},
{carta: "Mavren Fien", costo: 3, autor: "Darkeen", disponibilidad: true, comandante: false},
{carta: "Mari the Killing Quill", costo: 3, autor: "Bob Rey", disponibilidad: true, comandante: false},
{carta: "Creeping BloodSucker", costo: 2, autor: "Antonio Jose Manzenado", disponibilidad: true, comandante: false},
{carta: "Master of Dark Rites", costo: 1, autor: "Igor Kierluk", disponibilidad: true, comandante: false},
{carta: "The Three Weird Sisters", costo: 4, autor: "Nils Hamm", disponibilidad: true, comandante: false},
{carta: "Amamlia Benavides Aguirre", costo: 2, autor: "Alex Negrea", disponibilidad: true, comandante: false},
{carta: "Yahenni", costo: 3, autor: "Luis Lasahido", disponibilidad: true, comandante: false},
{carta: "Edgar Charmed Groom", costo: 4, autor: "Lucas Graciano", disponibilidad: true, comandante: false},
{carta: "Vampire Nighthawck", costo: 3, autor: "Jason Chan", disponibilidad: true, comandante: false},
{carta: "Vito Thorn oif the Dusk Rose", costo: 3, autor: "Lie Setiawan", disponibilidad: true, comandante: false},
{carta: "Twilight Prophet", costo: 4, autor: "David Astruga", disponibilidad: true, comandante: false},
{carta: "Reprieve", costo: 2, autor: "Justyna Dura", disponibilidad: true, comandante: false},
{carta: "Chaos Grap", costo: 3, autor: "Hisashi Momose", disponibilidad: true, comandante: false},
{carta: "Despark", costo: 2, autor: "Slawomir Maniak", disponibilidad: true, comandante: false},
{carta: "Auguished Unmaking", costo: 3, autor: "Luga Smilshkalne", disponibilidad: true, comandante: false},
{carta: "Terminate", costo: 2, autor: "Wayne Raymolds", disponibilidad: true, comandante: false},
{carta: "Generuous Gift", costo: 3, autor: "Key Walker", disponibilidad: true, comandante: false},
{carta: "Tibalt Trikeri", costo: 2, autor: "Anna Podewrona", disponibilidad: true, comandante: false},
{carta: "Frature", costo: 2, autor: "Miranda Meeks", disponibilidad: true, comandante: false},
{carta: "Path to Exile", costo: 1, autor: "Todo Lockwood", disponibilidad: true, comandante: false},
{carta: "Kolaghan Command", costo: 3, autor: "Darkeen", disponibilidad: true, comandante: false},
{carta: "Dire Tactics", costo: 2, autor: "Darkeen", disponibilidad: true, comandante: false},
{carta: "Utter End", costo: 4, autor: "Mark Winters", disponibilidad: true, comandante: false},
{carta: "Particion del alma", costo: 2, autor: "Kekai Kotami", disponibilidad: true, comandante: false},
{carta: "Sword of Splucher", costo: 1, autor: "Nagano", disponibilidad: true, comandante: false},
{carta: "Vindicate", costo: 3, autor: "Brian Snoddy", disponibilidad: true, comandante: false},
{carta: "Cleansing Nova", costo: 5, autor: "Noah Bradly", disponibilidad: true, comandante: false},
{carta: "Austere Command", costo: 6, autor: "Anna Steibauner", disponibilidad: true, comandante: false},
{carta: "Wind of Abadon", costo: 2, autor: "Noah Bradly", disponibilidad: true, comandante: false},
{carta: "Legion hechas cenizas", costo: 3, autor: "Arthur Nakhodin", disponibilidad: true, comandante: false},
{carta: "Hora de devastacion", costo: 6, autor: "Ryan Swanland", disponibilidad: true, comandante: false},
{carta: "Legion Landing", costo: 1, autor: "Stvetlin Velinov", disponibilidad: true, comandante: false},
{carta: "Pirexia Arena", costo: 3, autor: "Martina Fakova", disponibilidad: true, comandante: false},
{carta: "Dark Tutelage", costo: 3, autor: "Abigail Larson", disponibilidad: true, comandante: false},
{carta: "Blind Obedience", costo: 2, autor: "Olena Richards", disponibilidad: true, comandante: false},
{carta: "Vampire Rites", costo: 1, autor: "Harry Conway", disponibilidad: true, comandante: false},
{carta: "Arguels Blood Fast", costo: 2, autor: "Darkeen", disponibilidad: true, comandante: false},
{carta: "Rakdos Signet", costo: 2, autor: "Gred Hildebrant", disponibilidad: true, comandante: false},
{carta: "Trompó", costo: 1, autor: "Michael Sutfin", disponibilidad: true, comandante: false},
{carta: "Arcane Signet", costo: 2, autor: "Dan Skott", disponibilidad: true, comandante: false},
{carta: "Sol Ring", costo: 1, autor: "Mike Bierek", disponibilidad: true, comandante: false},
{carta: "Commander Sphere", costo: 3, autor: "Ryan Alexsander Lee", disponibilidad: true, comandante: false},
{carta: "Mardu Banner", costo: 3, autor: "Daniel Lungreen", disponibilidad: true, comandante: false},
{carta: "Orzhov Signet", costo: 2, autor: "Martina Pilceroba", disponibilidad: true, comandante: false},
{carta: "Boros Signet", costo: 2, autor: "Mike Sass", disponibilidad: true, comandante: false},
{carta: "Chromatic Lantern", costo: 3, autor: "Jung Park", disponibilidad: true, comandante: false},
{carta: "Cuidadela de Nicol Bolas", costo: 6, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "James Piack", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "James Piack", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "James Piack", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Andreas Rocha", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Zoltan Boros", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Jung Park", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Larry Magdunal", disponibilidad: true, comandante: false},
{carta: "Plains", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Mike Bierek", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Adam Paoquette", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Adam Paoquette", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Jhon Avon", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Aoiji Maiko", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Adam Paoquette", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Swamp", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Clife Childs", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Jose Hernaz", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Clife Childs", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Mountain", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Snowfield sinkhole", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Sulfurous Mire", costo: 0, autor: "Sam Burley", disponibilidad: true, comandante: false},
{carta: "Alphine Meadow", costo: 0, autor: "Adam Paoquette", disponibilidad: true, comandante: false},
{carta: "Maraña Sombra", costo: 0, autor: "Jhon Avon", disponibilidad: true, comandante: false},
{carta: "Thriving Heath", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Thriving Moor", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Thriving Bluff", costo: 0, autor: "JONAS De Ro", disponibilidad: true, comandante: false},
{carta: "Path of Ancestry", costo: 0, autor: "ALAYA Danner", disponibilidad: true, comandante: false},
{carta: "Commander Tower", costo: 0, autor: "Ryan Lee", disponibilidad: true, comandante: false}
];

